import type { CallLanguage } from "@/lib/contracts/call-language";

const english: Record<string, string> = {
  "일시정지": "Pause", "계속하기": "Resume", "일시정지 중": "Paused",
  "마이크와 안내 음성을 멈췄어요": "Microphone and voice guidance are paused",
  "사진 없이 바로 대화해요": "No photo needed",
  "이거 어떻게 버리지?": "How do I dispose of this?",
  "사진으로 시작하기": "Or start with a photo",
  "사진 찍기": "Take a photo",
  "사진 선택": "Upload a photo",
  "휴대폰 카메라로 촬영": "Use your phone camera",
  "앨범·파일에서 가져오기": "From your photos or files",
  "분리수거 길잡이": "RecycleGuide", "송파구": "Songpa-gu",
  "사진 찍고 물어보기": "Take a photo & ask", "바로 촬영": "Take a photo",
  "버릴 물건을 보여주세요": "Show us what you’re throwing away",
  "앨범에서 선택": "Choose from photos", "말로 물어보기": "Ask by voice",
  "사진 없이도 괜찮아요": "No photo needed", "다시 연결하기": "Try again",
  "음성 대화": "Voice guidance", "편하게 말씀하세요": "Go ahead, I’m listening",
  "듣고 있어요": "Listening", "버리는 방법을 확인하고 있어요": "Checking how to dispose of it",
  "이렇게 버려주세요": "Here’s what to do", "연결하고 있어요": "Connecting",
  "마이크가 꺼져 있어요": "Microphone is muted", "분리배출 안내 중": "Recycling guidance",
  "잠시만 기다려 주세요.": "Just a moment.", "무엇을 버리려고 하세요?": "What would you like to throw away?",
  "분리배출 사진 선택": "Choose a recycling photo", "분리배출 사진 촬영": "Take a recycling photo",
  "사진을 보내고 있어요": "Sending your photo", "소리 듣기": "Play audio",
  "마이크 켜기": "Unmute", "마이크 끄기": "Mute", "카메라 켜기": "Camera on",
  "카메라 취소": "Cancel camera", "카메라 끄기": "Camera off", "사진 보내기": "Send photo",
  "연결 취소": "Cancel", "안내 끝내기": "End guidance",
  "현재는 서울 송파구 기준으로 안내해요": "Currently based on Songpa-gu, Seoul rules",
  "대화·카메라 안내": "Voice & camera information",
  "AI 음성 안내입니다. 대화 중 마이크 소리가 OpenAI로 전달됩니다. 사진을 선택하면 음성 안내에 연결한 뒤 사진을 전달합니다. 카메라를 켜면 약 3초마다 화면 사진을 전달합니다.": "This is AI voice guidance. Your microphone audio is sent to OpenAI during a conversation. A selected photo is sent after voice guidance connects. While camera sharing is on, a still image is sent about every 3 seconds.",
  "앱은 음성·사진·대화를 저장하지 않습니다. 통화 종료나 페이지 이탈 시 마이크와 카메라를 끕니다. 한 통화는 최대 10분입니다.": "The app does not save audio, photos or conversations. The microphone and camera turn off when you end guidance or leave the page. Each session lasts up to 10 minutes.",
  "송파구 기준으로 안내하며, 성분이나 재질이 불분명하면 추가 확인이 필요합니다.": "Guidance follows Songpa-gu rules. Unclear materials or ingredients may need further checking.",
  "통화 중 보여주는 카메라 화면": "Camera shared during guidance",
  "카메라를 켜고 있어요": "Starting camera", "카메라 공유 중": "Sharing camera",
  "대화를 준비하고 있어요": "Getting ready", "언어": "Language",
  "안내를 끝내면 언어를 바꿀 수 있어요": "End guidance to change language",
  "통화에 연결하지 못했어요. 잠시 뒤 다시 시작해 주세요.": "Couldn’t connect. Please try again shortly.",
  "통화 연결을 확인하지 못했어요. 다시 시작해 주세요.": "Couldn’t verify the connection. Please try again.",
  "통화 연결이 끊겼어요. 다시 시작해 주세요.": "The connection was lost. Please try again.",
  "카메라 화면을 보내지 못했어요. 음성 대화는 계속할 수 있어요.": "Couldn’t share the camera. You can keep talking.",
  "답변 연결에 문제가 생겼어요. 다시 시작해 주세요.": "There was a problem receiving the answer. Please try again.",
  "답변이 중간에 끊겼어요. 다시 설명해 달라고 말씀해 주세요.": "The answer was cut short. Please ask for it again.",
  "대화 연결에 문제가 생겼어요. 다시 시작해 주세요.": "There was a connection problem. Please try again.",
  "연결이 오래 걸리고 있어요. 다시 시작해 주세요.": "The connection timed out. Please try again.",
  "HTTPS로 접속해야 마이크를 사용할 수 있어요.": "Open this page over HTTPS to use the microphone.",
  "마이크 연결이 끝났어요. 다시 시작해 주세요.": "The microphone disconnected. Please try again.",
  "통화가 끊겼어요. 다시 시작해 주세요.": "The conversation disconnected. Please try again.",
  "통화 연결에 문제가 생겼어요. 다시 시작해 주세요.": "Couldn’t connect. Please try again.",
  "통화를 준비하지 못했어요. 다시 시작해 주세요.": "Couldn’t start voice guidance. Please try again.",
  "통화를 연결하지 못했어요. 다시 시작해 주세요.": "Couldn’t connect. Please try again.",
  "마이크 사용을 허용한 뒤 다시 시작해 주세요.": "Allow microphone access, then try again.",
  "카메라 연결이 끝났어요. 음성 대화는 계속할 수 있어요.": "The camera disconnected. You can keep talking.",
  "카메라를 켜지 못했어요. 사진을 보내거나 말로 설명해 주세요.": "Couldn’t open the camera. Send a photo or describe the item.",
  "사진을 보내지 못했어요. 다시 골라 주세요.": "Couldn’t send the photo. Please select it again.",
  "사진을 열지 못했어요. 다른 사진을 골라 주세요.": "Couldn’t open the photo. Please choose another.",
  "사진을 보내지 못했어요. 더 가까이 찍은 사진을 골라 주세요.": "Couldn’t send the photo. Try a closer shot.",
  "사진 한 장은 5MB 이하여야 해요. 크기를 줄여 다시 선택해 주세요.": "Photos must be 5 MB or smaller. Resize and try again.",
  "비어 있는 사진이에요. 다른 사진을 선택해 주세요.": "This photo is empty. Please choose another.",
  "사진 파일을 선택해 주세요. JPG, PNG, WebP를 지원해요.": "Choose a JPG, PNG or WebP image.",
  "이 브라우저에서는 HEIC 사진을 열 수 없어요. JPG로 변환하거나 카메라로 다시 촬영해 주세요.": "This browser can’t open HEIC photos. Convert to JPG or take a new photo.",
  "사진을 열 수 없어요. JPG, PNG 또는 WebP 사진을 다시 선택해 주세요.": "Couldn’t open the photo. Choose a JPG, PNG or WebP image.",
  "사진 크기를 읽을 수 없어요. 다른 사진을 선택해 주세요.": "Couldn’t read the image size. Please choose another photo.",
  "사진을 변환할 수 없어요. JPG 사진을 선택해 주세요.": "Couldn’t convert the photo. Choose a JPG image.",
  "변환한 사진이 5MB를 넘어요. 사진 크기를 줄여 다시 선택해 주세요.": "The converted photo exceeds 5 MB. Resize and try again.",
};
export function callText(language: CallLanguage, text: string) {
  return language === "en" ? english[text] ?? text : text;
}
export function callError(language: CallLanguage, text: string) {
  return language === "en" ? english[text] ?? "Something went wrong. Please try again." : text;
}
